In [1]:
import pandas as pd

In [2]:
csv_sumary_path = "./Autofill_Sumary/Information_License_plate.xlsx"
data = pd.read_excel(csv_sumary_path, converters={'Biển số phần 2':str})

In [3]:
# Print head rows 
data.head()

# Print tail rows
data.tail()

,Biển số phần 1,Biển số phần 2,Chủ xe,Địa chỉ,Số CMND/CCCD,Số điện thoại,Ngày cấp,Bến Tre,Loại xe,Nhãn hiệu,...,Ngày đăng ký mới,Đăng ký xe có giá trị,Ngày đăng ký lần đầu,Biển số cũ,Cải tạo,Ngày cải tạo,Thu hồi,Ngày thu hồi,Sang tên di chuyển đi,Ngày sang tên di chuyển
5,71C167672,57557,TRẦN THÁI AN,"132, Vang Quới Đông, Bình Đại, Bến Tre",318455455.0,837326541,2006-04-03,Bến Tre,Hai bánh từ 50-175 cm3,HONDA,...,2018-04-10,NaN,2017-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,71C190875,24346,NGUYỄN ĐỨC ANH,"66, Vang Quới Tây, Bình Đại, Bến Tre",321670981.0,918673775,2018-10-22,Bến Tre,Hai bánh từ 50-175 cm3,YAMAHA,...,2018-04-10,NaN,2017-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,71C126943,57573,PHẠM HOÀNG,"298, Bình Thắng, Bình Đại, Bến Tre",309542109.0,939763639,2001-01-13,Bến Tre,Hai bánh từ 50-175 cm3,YAMAHA,...,2018-04-10,NaN,2017-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,71C390875,37653,LÊ HOÀNG ĐÔ,"7/2, Giao Thạnh, Thạnh Phú, Bến Tre",364951257.0,913562476,2000-11-20,Bến Tre,Hai bánh từ 50-175 cm3,YAMAHA,...,2018-04-10,NaN,2017-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,71B4,00472,Lê Huỳnh Yến Nhi,"24/2, Thới Thạnh, Thạnh Phú, Bến Tre",NaN,383626591,2000-11-20,Bến Tre,NaN,NaN,...,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# Duyet 1 cot
num_plates_excel = list(data["Biển số phần 2"])
print(num_plates_excel)

['12345', '42342', '23423', '23423', '24342', '57557', '24346', '57573', '37653', '00472']

In [58]:
a = [0,  0, 4, 7,3]
num_plate_predict = ''.join(map(str, a))
print(num_plate_predict)
if len(num_plate_predict) == 5:
    print()
    if num_plate_predict in num_plates_excel:
            #print(num_plates_excel.index(num_plate_predict))
            print("100%")
    else:
        for num_plate in num_plates_excel:
            #print(num_plate[:4])
            #print(num_plate[:3] , num_plate[4])
            #print(num_plate[:2] , num_plate[-2:])
            #print(num_plate[0] , num_plate[-3:])
            #print(num_plate[-4:])
            for i in range(5):
                if num_plate.replace(num_plate[i], '') == num_plate_predict.replace(num_plate_predict[i], ''):
                    print("80%")            
            """
            if num_plate[:4] == num_plate_predict[:4] or \
                            (num_plate[:3] == num_plate_predict[:3] and  num_plate[4] == num_plate_predict[4]) or\
                            (num_plate[:2] == num_plate_predict[:2] and num_plate[-2:] == num_plate_predict[-2:]) or \
                            (num_plate[0] == num_plate_predict[0] and num_plate[-3:] == num_plate_predict[-3:]) or \
                            num_plate[-4:] == num_plate_predict[-4:]:
                
               print("80%")   
            elif num_plate[:3] == num_plate_predict[:3] or \
                            num_plate[1:4] == num_plate_predict[1:4] or \
                            num_plate[-3:] == num_plate_predict[-3:]:
                print("60%")
             """       
elif len(num_plate_predict) == 4: 
    for num_plate in num_plates_excel:
        for i in range(5):
            if num_plate.replace(num_plate[i], '') == num_plate_predict:
                print("80%")
        
        """
        if num_plate[:4] == num_plate_predict or \
                            (num_plate[:3] == num_plate_predict[:3] and  num_plate[4] == num_plate_predict[-1:]) or\
                            (num_plate[:2] == num_plate_predict[:2] and num_plate[-2:] == num_plate_predict[-2:]) or \
                            (num_plate[0] == num_plate_predict[0] and num_plate[-3:] == num_plate_predict[-3:]) or \
                            num_plate[-4:] == num_plate_predict:
            print("80%")
        """
        """   
        elif num_plate[:3] == num_plate_predict[:3] or \
                            (num_plate[:2] == num_plate_predict[:2] and (num_plate[3] == num_plate_predict[2] or num_plate[3] == num_plate_predict[3]) or\
                            (num_plate[1:4] == num_plate_predict[:2] and num_plate[-2:] == num_plate_predict[-2:]) or \
                            (num_plate[0] == num_plate_predict[0] and num_plate[-3:] == num_plate_predict[-3:]) or \
                            num_plate[-4:] == num_plate_predict:
        """

00473

80%

In [54]:
s = "13579"
print(s.replace(s[1], ''))
s.replace(s[2], '')

1579

'1379'